# Generated by Django 4.2.4 on 2024-08-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('cc_date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
    ]
