# Generated by Django 4.2.4 on 2024-08-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='dbo.chats',
        ),
    ]
