# Generated by Django 4.2.4 on 2024-08-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='cc_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
