# Generated by Django 4.2.4 on 2024-08-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_cc_date_alter_chatmessage_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DboChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cc_date', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dbo.chats',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
