# Generated by Django 4.2.4 on 2024-08-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_dbochats_delete_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DboChats',
        ),
    ]
