# Generated by Django 4.2.4 on 2024-08-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_temporaryuser_delete_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
