# Generated by Django 4.2.4 on 2024-08-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_temporaryuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='temporaryuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
